<?php

namespace CPASimUSante\H5pClaroline\Repository;

/**
 * H5pRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class H5pRepository extends \Doctrine\ORM\EntityRepository
{
}
